version: 0.0
os: linux
files:
  - source: /
    destination: ~/
file_exists_behaviour: OVERWRITE
hooks:
  - BeforeInstall: 
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: root
  - AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 300
      runas: root