version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/acebook
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 60
      runas: root
