version: 0.0
os: linux
files:
  - source: /
    destination: ~/acebook
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall: 
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 300
      runas: ec2-user
